config/routes.rb
Selfstarter::Application.routes.draw do
  root :to => 'campaigns#index'

  resources :campaigns do
    resources :cheers do
      resources :cheer_orders, only: %i(new create)
    end
  end

  resources :feedbacks

  match '/preorder'               => 'preorder#index', :via => [:get,:post]
  get 'preorder/checkout'
  match '/preorder/share/:uuid'   => 'preorder#share', :via => :get
  match '/preorder/ipn'           => 'preorder#ipn', :via => :post
  match '/preorder/prefill'       => 'preorder#prefill', :via => [:get,:post]
  match '/preorder/postfill'      => 'preorder#postfill', :via => [:get,:post]
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :brewery
  has_many :beers
  has_many :cheers
  has_many :cheer_orders

  monetize :goal_cents

  def pledged_amount
    @pledged_amount ||= begin
                          amount = cheer_orders.includes(:cheer).sum(:value_cents)
                          Money.new(amount, goal_currency)
                        end
  end

  def pledged_percentage
    (100 * pledged_amount / goal).to_i
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def show
    @campaign = Campaign.find(params[:id])
  end

  def index
    @campaigns = Campaign.all
  end
end

app/views/campaigns/index.html.haml
%div{:id => "campaigns", :class => "row"}
  - @campaigns.each do |campaign|
    .campaign.col-sm-4
      = link_to campaign_path(campaign) do
        %span=campaign.name
        = image_tag(campaign.image)
      .description
        %p.brewery= campaign.brewery.name
        -#%p= campaign.short_description
        %p.deadline="⏱ " + distance_of_time_in_words_to_now(campaign.deadline) + " left"

app/views/campaigns/show.html.haml
.center
  %h2= @campaign.name
.wrapper.clearfix.row
  = image_tag(@campaign.image, class: "campaign_cover col-sm-6 img-responsive")
  #backing.col-sm-6
    .row
      #backers.stats.col
        = number_with_delimiter Order.backers, :delimiter => ","
        %span= Settings.primary_stat
      .stats.col
        = humanized_money_with_symbol(@campaign.pledged_amount)
        %span
          of #{humanized_money_with_symbol(@campaign.goal)}
      #days.stats.col
        = distance_of_time_in_words_to_now(@campaign.deadline).gsub(/\D/, "")
        %span
          = distance_of_time_in_words_to_now(@campaign.deadline).gsub(/\d/, "").gsub("about", "")
          left
    .row
      - if @campaign.pledged_amount < @campaign.goal
        #progress_bg.small
          #progress{:style => "width: #{@campaign.pledged_percentage}%;"}
      - else
        #progress_bg
          #progress
          #progress_text
            = @campaign.pledged_percentage
            \% Funded
    .campaign_summary.row
      %h5= @campaign.brewery.name.upcase
      %p= "#{@campaign.brewery.rating} ⭐️"
      %p= @campaign.brewery.short_description

- @campaign.beers.each do |beer|
  .big_wrapper
    .wrapper
      %h5= "🍺 #{beer.name}"
      %p Super fancy beer, you'll like it for sure!!!

#cheer-with-us
  .center
    %h3 Cheer with us
  %ul
    - @campaign.cheers.each_with_index do |cheer, i|
      = link_to new_campaign_cheer_cheer_order_path(@campaign, cheer) do
        %li
          %b= "#{cheer.title} - #{humanized_money_with_symbol(cheer.value)}"
          %p= cheer.description
#feedback
  .center
    = link_to "Leave your feedback", new_feedback_path, class: "btn btn-info"